name: Gradle build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Runs the gradle tests in container fnonnenmacher/arrow-plasma-java
      run: |
        docker run \
        -v ${{ github.workspace }}:/app fnonnenmacher/arrow-plasma-java:0.5 \
        /bin/bash -c "cp /arrow/java/gandiva/target/arrow-gandiva-0.17.0.jar /app/libs && ./gradlew build"
    - name: Archive test reports
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: build/reports/tests/test
